### PR TITLE
Link back to the core Manifest for terminology, concepts; tidy.

### PR DESCRIPTION
**Pull request by anssiko**

### CODE REVIEW

**Comment by anssiko** [comment]
@marcoscaceres Can you review and merge? Btw. I do not seem to have privileges to merge PRs in this repo.

**Comment by marcoscaceres** [comment]
LGTM

**Comment by marcoscaceres** [comment]
about the permissions, I'll ping @darobin about that.

**Comment by anssiko** [comment]
Thanks!

**Pull request merged**
